// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkmn48AyqcNNtUhe7BY76ryGKEu6njpdM',
    appId: '1:1046272814865:web:23e86e784683db1b432cc7',
    messagingSenderId: '1046272814865',
    projectId: 'fixpro-b90fc',
    authDomain: 'fixpro-b90fc.firebaseapp.com',
    storageBucket: 'fixpro-b90fc.appspot.com',
    measurementId: 'G-QC0YSPRGGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkmn48AyqcNNtUhe7BY76ryGKEu6njpdM',
    appId: '1:1046272814865:android:6d3034509747a1b86066b0',
    messagingSenderId: '1046272814865',
    projectId: 'fixpro-b90fc',
    storageBucket: 'fixpro-b90fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkmn48AyqcNNtUhe7BY76ryGKEu6njpdM',
    appId: '1:1046272814865:ios:2946dada09c88b02432cc7',
    messagingSenderId: '1046272814865',
    projectId: 'fixpro-b90fc',
    storageBucket: 'fixpro-b90fc.appspot.com',
    iosBundleId: 'com.example.fixPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkmn48AyqcNNtUhe7BY76ryGKEu6njpdM',
    appId: '1:1046272814865:ios:2946dada09c88b02432cc7',
    messagingSenderId: '1046272814865',
    projectId: 'fixpro-b90fc',
    storageBucket: 'fixpro-b90fc.appspot.com',
    iosBundleId: 'com.example.fixPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkmn48AyqcNNtUhe7BY76ryGKEu6njpdM',
    appId: '1:1046272814865:web:12d88f102e29084f432cc7',
    messagingSenderId: '1046272814865',
    projectId: 'fixpro-b90fc',
    authDomain: 'fixpro-b90fc.firebaseapp.com',
    storageBucket: 'fixpro-b90fc.appspot.com',
    measurementId: 'G-TMR7RE46MS',
  );
}