// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx3Tjh2FPOeDj7gbGAle4Ey_vPqgywpVE',
    appId: '1:109677121478:web:23e86e784683db1b432cc7',
    messagingSenderId: '109677121478',
    projectId: 'fixpro-e07b3',
    authDomain: 'fixpro-e07b3.firebaseapp.com',
    storageBucket: 'fixpro-e07b3.appspot.com',
    measurementId: 'G-QC0YSPRGGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ZU0_ESGP82mJLPxYxLppf-q0PFK1E9k',
    appId: '1:109677121478:android:45a07023322e0779432cc7',
    messagingSenderId: '109677121478',
    projectId: 'fixpro-e07b3',
    storageBucket: 'fixpro-e07b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQcpUF2gDg-3WC22ygZTNsjmA6CIC73BI',
    appId: '1:109677121478:ios:2946dada09c88b02432cc7',
    messagingSenderId: '109677121478',
    projectId: 'fixpro-e07b3',
    storageBucket: 'fixpro-e07b3.appspot.com',
    iosBundleId: 'com.example.fixPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQcpUF2gDg-3WC22ygZTNsjmA6CIC73BI',
    appId: '1:109677121478:ios:2946dada09c88b02432cc7',
    messagingSenderId: '109677121478',
    projectId: 'fixpro-e07b3',
    storageBucket: 'fixpro-e07b3.appspot.com',
    iosBundleId: 'com.example.fixPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx3Tjh2FPOeDj7gbGAle4Ey_vPqgywpVE',
    appId: '1:109677121478:web:12d88f102e29084f432cc7',
    messagingSenderId: '109677121478',
    projectId: 'fixpro-e07b3',
    authDomain: 'fixpro-e07b3.firebaseapp.com',
    storageBucket: 'fixpro-e07b3.appspot.com',
    measurementId: 'G-TMR7RE46MS',
  );
}
